blank_issues_enabled: false
contact_links:
  - name: Diskussionen
    url: https://github.com/Vibe-Technologies-EU/xinvoice-feedback/discussions
    about: "Für offene Fragen, Ideen oder Gespräche nutze die Diskussionen."
